const board = [
  { type: "L", x: 1, y: 0, rotation: 270 },
  { type: "I", x: 1, y: 0, rotation: 0 },
  { type: "L", x: 5, y: 2, rotation: 90 },
  { type: "I", x: 7, y: 3, rotation: 90 },
  { type: "Z", x: 3, y: 2, rotation: 180 },
  { type: "T", x: 5, y: 2, rotation: 180 },
  { type: "S", x: 6, y: 2, rotation: 270 },
  { type: "Z", x: 7, y: 4, rotation: 270 },
  { type: "L", x: 5, y: 6, rotation: 0 },
  { type: "O", x: 3, y: 3, rotation: 0 },
  { type: "S", x: 3, y: 6, rotation: 0 },
  { type: "S", x: 1, y: 6, rotation: 0 },
  { type: "Z", x: 1, y: 5, rotation: 270 },
  { type: "L", x: 3, y: 4, rotation: 0 },
  { type: "L", x: 1, y: 5, rotation: 90 },
  { type: "T", x: 1, y: 3, rotation: 270 },
];
